- name: Resume EKS cluster
  hosts: localhost
  connection: local
  vars:
    optional_assume_role: "{{ lookup('ansible.builtin.env', 'OPTIONAL_ASSUME_ROLE_ARN') | default('', true) }}"
    assumed_role_creds: "{{ lookup('amazon.aws.aws_assume_role', role_arn=optional_assume_role, role_session_name='AnsibleEKSScaleSession') if optional_assume_role else {} }}"
    aws_env:
      AWS_ACCESS_KEY_ID: "{{ assumed_role_creds.access_key | default(omit) }}"
      AWS_SECRET_ACCESS_KEY: "{{ assumed_role_creds.secret_key | default(omit) }}"
      AWS_SESSION_TOKEN: "{{ assumed_role_creds.session_token | default(omit) }}"
  tasks:
    - name: Get EKS cluster node groups
      ansible.builtin.shell: aws eks list-nodegroups --cluster-name="{{ name }}"
      args:
        executable: /bin/bash
      register: node_groups_result
      environment: "{{ aws_env }}"

    - name: Resume paused EKS cluster
      ansible.builtin.shell: aws eks describe-nodegroup --cluster="{{ name }}" --nodegroup-name="{{ item }}" | eksctl scale nodegroup --cluster="{{ name }}" --nodes="{{ lookup('vars', item + '_size') }}" --name="{{ item }}"
      args:
        executable: /bin/bash
      loop: "{{ node_groups_result.stdout|from_json|json_query('nodegroups') }}"
      register: result
      environment: "{{ aws_env }}"
    
    - copy:
        content: "{{ result }}"
        dest: "qtorque_outputs.json"