- name: Stop Aws EC2 
  hosts: localhost
  connection: local
  tasks:
    - name: stop ec2 instance by its ID
      amazon.aws.ec2_instance:
        instance_ids:
          - "{{ id }}"
        region: "{{ (arn | split(':'))[3] }}"
        state: stopped
        wait: true
        
    - name: gather information about the ec2 instance
      amazon.aws.ec2_instance_info:
        instance_ids:
          - "{{ id }}"
      register: result
      
    - copy:
        content: {{ result }}
        dest: qtorque_outputs.json
