- name: Stop Aws RDS 
  hosts: localhost
  connection: local
  tasks:
    - name: stop aws rds instance by its ID
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ identifier }}"
        region: "{{ (arn | split(':'))[3] }}"
        state: started
        wait: false
      poll: 0

    - name: check aws rds status
      amazon.aws.rds_instance:
        region: "{{ (arn | split(':'))[3] }}"
        db_instance_identifier: "{{ identifier }}"
      register: result
      loop: "{{ range(1, 40) }}"
      loop_control:
        label: "DB status {{ result.db_instance_status }}. Retrying..."
        loop_var: result
        pause: 10

    - copy:
        content: "{{ result }}"
        dest: qtorque_outputs.json