- name: Start AWS RDS instance 
  hosts: localhost
  connection: local
  tasks:
    - name: start aws rds instance by its ID
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ DBInstanceIdentifier }}"
        state: started
        wait: true
        
    - name: gather information about the rds instance
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ DBInstanceIdentifier }}"
      register: result
      
    - copy:
        content: "{{ result }}"
        dest: qtorque_outputs.json