- name: Stop Aws RDS 
  hosts: localhost
  connection: local
  tasks:
    - name: stop aws rds instance by its ID
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ identifier }}"
        region: "{{ (arn | split(':'))[3] }}"
        state: stopped
        wait: false
      poll: 0
        
    - name: gather information about the rds instance
      amazon.aws.rds_instance:
        region: "{{ (arn | split(':'))[3] }}"
        db_instance_identifier: "{{ identifier }}"
      register: result
      loop: "{{ range(20) }}"
      when: result.db_instance_status != 'stopped'
      loop_control:
        label: "Current status {{ result.db_instance_status }}"
        pause: 30
      
    - copy:
        content: "{{ result }}"
        dest: qtorque_outputs.json