- name: Stop Aws RDS 
  hosts: localhost
  connection: local
  tasks:
    - name: stop aws rds instance by its ID
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ identifier }}"
        region: "{{ (arn | split(':'))[3] }}"
        state: started
        wait: false
      poll: 0

    - name: check aws rds status
      amazon.aws.rds_instance:
        region: "{{ (arn | split(':'))[3] }}"
        db_instance_identifier: "{{ identifier }}"
      register: result
    
    - name: Wait for RDS instance to start
      wait_for:
        timeout: 600  # Adjust the timeout as needed
        sleep: 30     # Adjust the sleep interval as needed
        state: "started"
      register: log
      until: log.elapsed < 600

    - name: Show log of attempts
      debug:
        var: log

    - copy:
        content: "{{ result }}"
        dest: qtorque_outputs.json