- name: Stop Aws RDS 
  hosts: localhost
  connection: local
  tasks:
    - name: stop aws rds instance by its ID
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ id }}"
        db_instance_class: "{{ instance_class }}"
        master_username: "{{ username }}"
        master_user_password: "{{ password }}"
        region: "{{ (arn | split(':'))[3] }}"
        engine: "{{ engine }}"
        state: stopped
        wait: true
        
    - name: gather information about the rds instance
      amazon.aws.rds_instance:
        region: "{{ (arn | split(':'))[3] }}"
        db_instance_identifier: "{{ id }}"
      register: result
      
    - copy:
        content: "{{ result }}"
        dest: qtorque_outputs.json