- name: Start Aws RDS 
  hosts: localhost
  connection: local
  tasks:
    - name: start aws rds instance by its ID
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ identifier }}"
        region: "{{ (arn | split(':'))[3] }}"
        state: started
        wait: false
      poll: 0

    - name: gather information about the rds instance
      amazon.aws.rds_instance:
        region: "{{ (arn | split(':'))[3] }}"
        db_instance_identifier: "{{ identifier }}"
      register: result
      changed_when: result.db_instance_status == 'available'
      loop_control:
        label: "DB status {{ result.db_instance_status }}. Retrying..."
        pause: 20
      with_sequence: 0-50
      when: not result.changed
      
    - copy:
        content: "{{ result }}"
        dest: qtorque_outputs.json