- name: Start AWS RDS instance 
  hosts: localhost
  connection: local
  tasks:
    - name: start aws rds instance by its ID
      amazon.aws.rds_instance:
        db_instance_identifier: "{{ identifier }}"
        region: "{{ (arn | split(':'))[3] }}"
        state: started
        wait: false
      poll: 0
        
    - name: gather information about the rds instance
      amazon.aws.rds_instance:
        region: "{{ (arn | split(':'))[3] }}"
        db_instance_identifier: "{{ identifier }}"
      register: result
      until: result.db_instance_status == 'available'
      retries: 20
      delay: 30
      
    - copy:
        content: "{{ result }}"
        dest: qtorque_outputs.json