- name: Permanently delete an Azure MsSQL instance.
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    federated_login:
      is_set: "{{ lookup('ansible.builtin.env', 'AZURE_FEDERATED_TOKEN_FILE', default=undefined) }}"
  tasks:
    - name: az federated login
      ansible.builtin.shell: az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE)
      when: federated_login.is_set is defined
      args:
        executable: /bin/bash
        
    - name: Delete an Azure MsSQL instance by it's name.
      azure_rm_sqldatabase:
        name: "{{ name }}"
        resource_group : "{{ (id | split('/'))[4] }}"
        server_name : "{{ server_name }}"
        state: "absent"
      register: result

    # - copy:
    #     content: "{{ result }}"
    #     dest: qtorque_outputs.json