- name: Deallocate Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    federated_login:
      is_set: "{{ lookup('ansible.builtin.env', 'AZURE_FEDERATED_TOKEN_FILE', default=undefined) }}"
  tasks:
    - name: az federated login
      ansible.builtin.shell: az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE)
      when: federated_login.is_set is defined
      args:
        executable: /bin/bash
    
    - name: set subscription
      ansible.builtin.shell: az account set --subscription {{ id | regex_search('(?<=/subscriptions/)([a-fA-F0-9-]+)') }}
      args:
        executable: /bin/bash
    
    - name: try deallocate virtual machine
      block:     
        - name: Deallocate virtual machine
          azure_rm_virtualmachine:
            resource_group: "{{ resource_group_name }}"
            name: "{{ name }}"
            allocated: no
          register: result
      rescue:
        - name: Deallocate virtual machine using cli
          ansible.builtin.shell: az vm deallocate -g {{ resource_group_name }} -n {{ name }}
          args:
            executable: /bin/bash
          register: result
        - name: Get details
          azure_rm_virtualmachine:
            resource_group: "{{ resource_group_name }}"
            name: "{{ name }}"
          register: result

    - copy:
        content: "{{ result }}"
        dest: "qtorque_outputs.json"
