- name: Permanently delete an Azure MySQL flexible instance.
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    federated_login:
      is_set: "{{ lookup('ansible.builtin.env', 'AZURE_FEDERATED_TOKEN_FILE', default=undefined) }}"

  tasks:
    - name: az federated login
      ansible.builtin.shell: az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE)
      when: federated_login.is_set is defined
      args:
        executable: /bin/bash
    
    - name: set subscription
      ansible.builtin.shell: az account set --subscription {{ id | regex_search('(?<=/subscriptions/)([a-fA-F0-9-]+)') }}
      args:
        executable: /bin/bash
    
    - name: Delete an Azure MySQL flexible instance by it's name.
      ansible.builtin.shell: az mysql flexible-server db delete --resource-group "{{ resource_group_name }}" --server-name "{{ server_name }}" --database-name "{{ name }}"
      args:
        executable: /bin/bash
      register: result
    
    - copy:
        content: "{{ result }}"
        dest: "qtorque_outputs.json"