- name: Stop GCP vm
  hosts: localhost
  connection: local

  collections:
    - google.cloud

  vars:
    service_account_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"

  tasks:
    - name: Stop the GCP vm by its name
      google.cloud.gcp_compute_instance:
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        project: "{{ project }}"
        zone: "{{ zone }}"
        name: "{{ name }}"
        status: TERMINATED
        
    - name: gather information about the vm instance
      google.cloud.gcp_compute_instance_info:
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_file }}"
        project: "{{ project }}"
        zone: "{{ zone }}"
        filters:
          - "name={{ name }}"
      register: vm_info
      
    - copy:
        content: "{{ vm_info }}"
        dest: qtorque_outputs.json
